#!/bin/bash

function cd() {
    builtin cd "$@" && ls -F
    pwd
}

mcd() {
    mkdir -p $1
    cd $1
}

update() {
    sudo apt-get update
    sudo apt-get upgrade
    sudo apt-get dist-upgrade

    echo "==Do you wish to clean?=="
    select yn in "Yes" "No"; do
        case $yn in
        Yes)
            sudo du -sh /var/cache/apt/archives
            sudo apt-get clean
            sudo apt-get autoremove --purge
            break
            ;;
        No) break ;;
        esac
    done
}

function shutDownTimer() {
    echo "======shutDown======"
    echo "1.Timer"
    echo "2.Clock (1:00)"
    echo "3.Now"
    echo "4.Cancel"
    echo "5.Exit"

    while :; do
        read INPUT_STRING
        case $INPUT_STRING in
        1)
            read -p "How many minutes:" TIME
            sudo shutdown -P +$TIME
            echo "1.Timer"
            echo "2.Clock (1:00)"
            echo "3.Now"
            echo "4.Cancel"
            echo "5.Exit"
            ;;
        2)
            read -p "What time:"CLOCK
            sudo shutdown -P $CLOCK
            echo "1.Timer"
            echo "2.Clock (1:00)"
            echo "3.Now"
            echo "4.Cancel"
            echo "5.Exit"
            ;;
        3)
            sudo shutdown -P now
            echo "1.Timer"
            echo "2.Clock (1:00)"
            echo "3.Now"
            echo "4.Cancel"
            echo "5.Exit"
            ;;
        4)
            sudo shutdown -c
            echo "1.Timer"
            echo "2.Clock (1:00)"
            echo "3.Now"
            echo "4.Cancel"
            echo "5.Exit"
            ;;
        5)
            break
            ;;
        *)
            echo "pick 1, 2, 3, 4 or 5"
            ;;
        esac
    done
    echo
}
