#!/bin/bash
functions(){
    echo "mcd"
    echo "update"
    echo "calendar"
    echo "shutDownTimer"
    echo "scripts"
    echo "utubeAudio"
    echo "utubeVideo"
    echo "utubePlaylist"
    echo "findService"
    echo "killService"
    echo "mic"
    
}

cd() {
    builtin cd "$@" && ls -F
    pwd
}

mcd() {
    mkdir -p $1
    cd $1
}

findService(){
    pgrep -l -u helgi
}
killService()
{
    sudo kill -9 $1
}

mic(){
    amixer set Capture toggle && amixer get Capture | grep '\[off\]' && notify-send "MIC switched OFF" || notify-send "MIC switched ON"
}

update() {
    sudo cp -f ~/Dropbox/scripts/functions /usr/local/bin
    sudo cp -f ~/Dropbox/scripts/alias /usr/local/bin
    echo "functions and scripts updated"
    
    sudo cp -f  ~/Dropbox/settingsFiles/mpv.conf /etc/mpv
    echo "MPV player updated"
    
    sudo cp ~/Dropbox/settingsFiles/newsboat/config ~/.newsboat/urls
    sudo cp ~/Dropbox/settingsFiles/newsboat/urls ~/.newsboat/urls
    echo "Newsboat updated"
    
    sudo cp ~/Dropbox/settingsFiles/TerminatorConfig/config ~/.config/terminator/
    echo "Terminator updated"
    
    sudo cp -f -r ~/Dropbox/wallpapers/ ~/Pictures/
    echo "Wallpapers updated"
    
    case $HOSTNAME in
        helgi-u-pc)
            sudo cp -f ~/Dropbox/scripts/directoriesPC /usr/local/bin
            echo "directoriesPC updated"
            
            sudo cp -f /mnt/d232cad4-4a88-4576-a779-e86ca93d0612/Projects/C++/calendar/bin/calendar /usr/local/bin
            echo "c++Calendar updated"
        ;;
        
        helgi-u-laptop)
            sudo cp -f ~/Dropbox/scripts/directoriesLaptop /usr/local/bin
            echo "directoriesLaptop updated"
            
            
            sudo cp -f /mnt/c42d2694-1ea4-43ae-a2b8-9f6e9c5ef480/Projects/C++/calendar/bin/calendar /usr/local/bin
            echo "c++Calendar updated"
        ;;
        
        *) echo "No host name found!!" ;;
    esac
    
    source ~/.bashrc
    
    sudo apt-get update
    sudo apt-get upgrade
    sudo apt-get dist-upgrade
    echo "System updated"
    echo ""
    
    sudo du -sh /var/cache/apt/archives
    sudo apt-get clean
    sudo apt-get autoremove --purge
    echo "System cleaned"
}

function calendar() {
    '/usr/local/bin/calendar' $@
}

function shutDownTimer() {
    
    if [ "$1" ]; then
        sudo shutdown -P +$1
        exit
    else
        echo "======shutDown======"
        echo "1.Timer"
        echo "2.Clock (1:00)"
        echo "3.Now"
        echo "4.Cancel"
        echo "5.Exit"
        while :; do
            read -p "Make your choise:" INPUT_STRING
            case $INPUT_STRING in
                1)
                    read -p "How many minutes:" TIME
                    sudo shutdown -P +$TIME
                    break
                ;;
                2)
                    read -p "What time:"CLOCK
                    sudo shutdown -P $CLOCK
                    break
                ;;
                3)
                    sudo shutdown -P now
                    break
                ;;
                4)
                    sudo shutdown -c
                    break
                ;;
                5)
                    break
                ;;
                *)
                    echo "pick 1, 2, 3, 4 or 5"
                ;;
            esac
        done
        echo
        exit
    fi
}

scripts(){
    code ~/Dropbox/scripts
}



utubeAudio(){
    youtube-dl -x --audio-format mp3  $1
}

utubePlayList(){
    youtube-dl -f 136+140 -o '~/Downloads/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' $1
}

utubeVideo(){
    youtube-dl $1
}
