#!/bin/bash
echo "======Nodejs======"
sudo apt-get remove nodejs
sudo apt-get purge nodejs
cd ~
sudo apt install curl
curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
sudo apt install nodejs
nodejs --version
read -p "Continuing in 3 seconds..." -t 3

sudo apt-get remove docker docker-engine docker.io
sudo apt install docker.io
sudo usermod -aG docker ${USER}

sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

echo -p "=====Awscli====="
sudo apt install awscli
aws configure

techcarerepos() {
    cd ~
    echo "Example folder destination: Desktop/techcare"
    while read -ep "Enter folder path location: " file_dir; do
        if [ -d "${file_dir}" ]; then
            echo "${file_dir} already exists - please enter a valid directory path."
        else
            mkdir -p "${file_dir}"
            cd ${file_dir}
            git clone git@github.com:techcare-fo/api.git
            git clone git@github.com:techcare-fo/app.git
            break
        fi
    done
}

echo "Do you wish to clone techcare repos api/app?"
select yn in "Yes" "No"; do
    case $yn in
        Yes)
            techcarerepos
            break
        ;;
        No) break ;;
    esac
done
