#!/bin/bash

SECONDS=0
COUNTER=1
END=27

echo "---------------------------------------------------"
date
echo "---------------------------------------------------"
echo "Installation BASH Script For Ubuntu 18.04.2 LTS"
echo "v1.0 (04-07-2019)"
echo "---------------------------------------------------"
echo ""
echo ""
echo "---------Before starting---------"
echo "Install DROPBOX"
read -p "Press [enter] to continue:"
echo "Add LASTPASS to Firefox"
read -p "Press [enter] to continue:"
echo "Login your Firefox USER"
read -p "Press [enter] to continue:"
echo "If on PC change in firefox: layout.css.devPixelsPerPx to 1.3"
read -p "Press [enter] to continue:"


countdown() (
    IFS=:
    set -- $*
    secs=$((${1#0} * 3600 + ${2#0} * 60 + ${3#0}))
    while [ $secs -gt 0 ]; do
        sleep 1 &
        printf "\r%02d:%02d:%02d" $((secs / 3600)) $(((secs / 60) % 60)) $((secs % 60))
        secs=$(($secs - 1))
        wait
    done
    echo
)
echo "Installation starts in 5 seconds!"
countdown "00:00:5" # 10 sec

echo "HERE WE GO!"
sleep 2

sudo ubuntu-drivers autoinstall

sudo apt install curl -y
sudo apt install nano -y


sudo apt-get install terminator -y
sudo mkdir ~/.config/terminator
sudo cp ~/Dropbox/settingsFiles/TerminatorConfig/config ~/.config/terminator/

sudo apt install gdebi-core -y
sudo apt install -y wget jq unzip
sudo apt install git -y
sudo apt install gnome-tweak-tool -y
sudo snap install htop -y
sudo apt-get install locate -y

sudo apt-get install curl python-software-properties
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs

curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn

sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"
sudo apt update
sudo apt install adobe-flashplugin browser-plugin-freshplayer-pepperflash -y





gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
gsettings set org.gnome.shell.extensions.dash-to-dock show-trash true
gsettings set org.gnome.shell.extensions.desktop-icons show-trash false
gsettings set org.gnome.shell.extensions.dash-to-dock show-apps-at-top true
sudo echo "PS1='\[\033[1;36m\]\u\[\033[1;31m\]@\[\033[1;32m\]\h:\[\033[1;35m\]\w\[\033[1;31m\]\$\[\033[0m\]'" >>~/.bashrc
sudo chown -R $USER: $HOME
git config --global user.email "helgipoulsen@hotmail.com"
git config --global user.name "Helgi Poulsen"
sudo gpasswd --add ${USER} dialout
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
fs.inotify.max_user_watches=524288
sudo sed -ibak -e s/^enabled\=1$/enabled\=0/ /etc/default/apport

sudo apt install chrome-gnome-shell
cd ~/Dropbox/scripts/gnomeExtensions/
./install-gnome-extensions.sh --enable --file gExtensions
cd

rsakey() {
    echo "======RSAKEY======"
    echo "1.Generate key"
    echo "2.show key"
    echo "3.exit"
    
    while :; do
        read INPUT_STRING
        case $INPUT_STRING in
            1)
                ssh-keygen -t rsa -b 4096
                echo "1.Generate key"
                echo "2.show key"
                echo "3.exit"
            ;;
            2)
                sudo cat ~/.ssh/id_rsa.pub
                echo "1.Generate key"
                echo "2.show key"
                echo "3.exit"
            ;;
            3)
                break
            ;;
            *)
                echo "pick 1, 2 or 3"
            ;;
        esac
    done
    echo
    echo "remember to copy your key to github"
}

echo "==Do you wish to setup RSA key?=="
select yn in "Yes" "No"; do
    case $yn in
        Yes)
            rsakey
            break
        ;;
        No) break ;;
    esac
done

echo "Add your rsa key to github!"
read -p "Press [enter] to continue"

#youtube-dl
sudo apt-get install python-pip -y
sudo pip install youtube-dl
touch ~/.config/youtube-dl.conf
echo "--output \"~/Downloads/%(title)s.%(ext)s\"" >> ~/.config/youtube-dl.conf

#RSS for terminal
sudo snap install newsboat
sudo cp ~/Dropbox/settingsFiles/newsboat/config ~/snap/newsboat/1471/.newsboat
sudo cp ~/Dropbox/settingsFiles/newsboat/urls ~/snap/newsboat/1471/.newsboat

#Shutter
sudo add-apt-repository ppa:linuxuprising/shutter
sudo apt install shutter -y

#Nordvpn
sudo apt-get install network-manager-openvpn-gnome
sudo apt-get install network-manager-openvpn
sudo apt-get install network-manager-pptp

#VideoPlayer
sudo add-apt-repository ppa:mc3man/mpv-tests
sudo apt update && sudo apt install mpv
sudo cp -f  ~/Dropbox/settingsFiles/mpv.conf /etc/mpv

#Code
sudo apt update
sudo apt install software-properties-common apt-transport-https wget
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
sudo apt update
sudo apt install code

#Spotify
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90 2EBF997C15BDA244B6EBF5D84773BD5E130D1D45
echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
sudo apt-get update
sudo apt-get install spotify-client

#Libreoffice
sudo add-apt-repository ppa:libreoffice/ppa
sudo apt-get update
sudo apt-get install libreoffice

#Torrents
sudo apt install deluge -y

#UML Diagrams
sudo apt-get install umbrello -y

#PDF
sudo apt-get install okular -y

#Audio Player
sudo apt-get install clementine -y

#SQL Postgres
sudo apt-get install postgresql postgresql-contrib -y
echo 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main' >>/etc/apt/sources.list.d/pgdg.list
sudo apt install vlcwget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get install postgresql-10

#Paint
sudo apt-get install pinta -y

#Taking notes
wget "https://github.com/Kilian/fromscratch/releases/download/v1.4.3/FromScratch_1.4.3_amd64.deb"
sudo gdebi FromScratch_1.4.3_amd64.deb -y

#Podcast
sudo apt install gpodder

#Communication
wget https://downloads.slack-edge.com/linux_releases/slack-desktop-3.3.8-amd64.deb
sudo apt install ./slack-desktop-*.deb

#debs from dropbox software
#Quick launch application
sudo apt install '/home/helgi/Dropbox/software/ulauncher_4.4.0.r1_all.deb'

#Radiotray-ng
sudo apt install '/home/helgi/Dropbox/software/radiotray-ng_0.2.7_ubuntu_19.10_amd64.deb'
sudo cp ~/Dropbox/settingsFiles/radiotray/bookmarks.json ~/.config/radiotray-ng
#simplenote
sudo apt install '/home/helgi/Dropbox/software/Simplenote-linux-1.10.0-amd64.deb'
#Skype
sudo apt install '/home/helgi/Dropbox/software/skypeforlinux-64.deb'

#mailSpring
sudo apt install 'mailspring-1.7.2-amd64.deb'


#Gaming
sudo apt install '/home/helgi/Dropbox/software/steam_latest.deb'
#------------------------

#Scripts
sudo cp ~/Dropbox/scripts/functions /usr/local/bin
sudo cp ~/Dropbox/scripts/alias /usr/local/bin
sudo cp ~/Dropbox/scripts/techcare /usr/local/bin
sudo echo "source /usr/local/bin/alias" >>~/.bashrc
sudo echo "source /usr/local/bin/functions" >>~/.bashrc
sudo echo "source /usr/local/bin/techcare" >>~/.bashrc
sudo cp -r ~/Dropbox/wallpapers ~/Pictures

#Adding bookmarks to Files overview
echo "file:///home/helgi/Dropbox" >> ~/.config/gtk-3.0/bookmarks

case $HOSTNAME in
    helgi-u-pc)
        sudo cp ~/Dropbox/scripts/directoriesPC /usr/local/bin
        sudo echo "source /usr/local/bin/directoriesPC" >>~/.bashrc
        sudo cp /mnt/d232cad4-4a88-4576-a779-e86ca93d0612/Projects/C++/calendar/bin/calendar /usr/local/bin
        sudo echo "/usr/local/bin/calendar" >>~/.bashrc
        
        #Adding bookmarks to Files overview
        echo "file:///mnt/d232cad4-4a88-4576-a779-e86ca93d0612/Projects"  >> ~/.config/gtk-3.0/bookmarks
        echo "file:///mnt/d232cad4-4a88-4576-a779-e86ca93d0612/Downloads"  >> ~/.config/gtk-3.0/bookmarks
    ;;
    helgi-u-laptop)
        sudo cp ~/Dropbox/scripts/directoriesLaptop /usr/local/bin
        sudo echo "source /usr/local/bin/directoriesLaptop" >>~/.bashrc
        sudo cp -f '/mnt/9c17aad5-7b2f-453b-9ae2-085895278529/Projects/C++/calendar/bin/calendar' /usr/local/bin/
        sudo echo "/usr/local/bin/calendar" >>~/.bashrc
        
        #Adding bookmarks to Files overview
        echo "file:///mnt/9c17aad5-7b2f-453b-9ae2-085895278529/Projects"  >> ~/.config/gtk-3.0/bookmarks
        echo "file:///mnt/9c17aad5-7b2f-453b-9ae2-085895278529/Downloads"  >> ~/.config/gtk-3.0/bookmarks
    ;;
    *) echo "How did I get in the middle of nowhere?" ;;
esac

source ~/.bashrc

#removing downloaded files
sudo rm ~/Dropbox/scripts/download?platform=linuxDeb
sudo rm ~/Dropbox/scripts/FromScratch_1.4.3_amd64.deb
sudo rm ~/Dropbox/scripts/packages-microsoft-prod.deb
sudo rm ~/Dropbox/scripts/skypeforlinux-64.deb
sudo rm ~/Dropbox/scripts/slack-desktop-3.3.8-amd64.deb

sudo rm ~/download?platform=linuxDeb
sudo rm ~/FromScratch_1.4.3_amd64.deb
sudo rm ~/packages-microsoft-prod.deb
sudo rm ~/skypeforlinux-64.deb
sudo rm ~/slack-desktop-3.3.8-amd64.deb

#Snaps
sudo snap install postman
sudo snap install squirrelsql
sudo snap install gitkraken

#dual wallpaper
sudo apt install flatpak
sudo apt install gnome-software-plugin-flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.gabmus.hydrapaper

bigDownloads() {
    echo "======Big Downloads======"
    echo "1.Generate key"
    echo "2.show key"
    echo "3.exit"
    
    while :; do
        read INPUT_STRING
        case $INPUT_STRING in
            1)
                #eclipse
                sudo snap install eclipse --classic
                #Latex
                sudo apt install texlive-full -y
                sudo apt-get install texlive-bibtex-extra biber -y
                #unity
                sudo apt install gdebi
                wget http://beta.unity3d.com/download/ee86734cf592/unity-editor_amd64-2017.2.0f3.deb
                sudo gdebi unity-editor_amd64-2017.2.0f3.deb
            ;;
            
            2)
                break
            ;;
            *)
                echo "pick 1 or 2"
            ;;
        esac
    done
    echo
}

echo "==Do you wish to the big downloads?=="
select yn in "Yes" "No"; do
    case $yn in
        Yes)
            bigDownloads
            break
        ;;
        No) break ;;
    esac
done

#Computer info
sudo apt install neofetch
neofetch
echo "---------------------------------------------------"
duration=$SECONDS
echo "$(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed."
echo "Please Reboot!"
echo "---------------------------------------------------"
